### ISSUE TITLE
Discuss Age Covariate Problem in JoE Response

### ISSUE THREAD

**Issue by davebridges** [BridgesLab/CushingAcromegalyStudy#53]
Quynh can you put together a response to this comment. One option is including in the supplement the analysis in which age and body weight are used as covariates, or just age (not body weight) as a covariate.  My sense is that we are underpowered, especially if we account for both age and body weight, so maybe giving an actual value to the statistical power would help too.  In the end we can point out that the genes we have validated in mice alleviate this problem.  The relevant comment was:

* The statistics section does not mention the use of a model that corrects for age in the Cushings and non Cushings groups. Has this been done? If so it should be addressed in this section and in the results. If not, a statistical model that corrects for age should be applied and reported.

**Comment by qtran1** [comment]
OK! Will do!

On Apr 9, 2015, at 8:10 AM, Dave Bridges <notifications@github.com<mailto:notifications@github.com>> wrote:


Quynh can you put together a response to this comment. One option is including in the supplement the analysis in which age and body weight are used as covariates, or just age (not body weight) as a covariate. My sense is that we are underpowered, especially if we account for both age and body weight, so maybe giving an actual value to the statistical power would help too. In the end we can point out that the genes we have validated in mice alleviate this problem. The relevant comment was:

  *   The statistics section does not mention the use of a model that corrects for age in the Cushings and non Cushings groups. Has this been done? If so it should be addressed in this section and in the results. If not, a statistical model that corrects for age should be applied and reported.

**Comment by qtran1** [comment]
We have 9 obese (BMI > 30)  and 7 not obese (BMI <= 30). Within the obese group, we have 6 control and 3 Cushing's patients. Within the non-obese group, we have 5 control and 2 Cushing's patients.

Age: Cushing's patients age ranges from 26 to 50 years old. Age of control patients ranges from 48 to 74. We don't have any control patients that were younger than 40 years old nor any cushion's patients that were older than 60. We have 6 control and 2 cushing's patients that had the age greater than 40 but <=60.

I do not think our design allows us to add age as a covariate in the model, but we can look at the effect of the disease in the age group 40 to 60. Since we only have 2 cushing's patients in this age group, we don't have enough power to detect changes in gene expression. However, an analysis was done and saved for this age group (40,60]. There are only 11 genes were significantly changed, this is probably due to small sample size, lack of statistical power.

To address the review concern, I found this paper PMID: 23889843, which analyzed gene expression changes with age in subcutaneous adipose tissue in 856 female twins in the age range of 39-85 years (mean age 59.3 years). I downloaded this gene list to compare with our genes that are affected by Cushing's after adjusting for BMI in order to demonstrate that the genes found in our study were not confounded by age (see commit 3ad8c34 and 6b4723f).

A power analysis using RNASeqPower was used to calculate the power for different sample size with these criteria:
1. depth of coverage: 10x
2. coefficient of variation: 0.4
3. alpha = 0.05
4. effect size or fold change: 1.75 or 2
4. Sample size: 2,3,5,6,7,9

                1.75         2
2    0.1942153        0.2740564
3    0.2690099        0.3839670
5    0.4111184         0.5751081
6    0.4764587        0.6534088
7    0.5371533        0.7201176
9    0.6436299        0.8221794

This is the strategy for addressing one of the concerns of a reviewer. A formal response will be written in the JoE Response file.

**Comment by davebridges** [comment]
Sounds good.  So according to the last table, because of our small sample size we only will be able to determine a 2 fold changed gene 27% of the time.  I think that is a good argument.  When you say 11 genes were changed, do you mean by Cushing's after adjustment for age?  If so, lets list those 11 genes, their age-adjusted fold change and p-values in a table in the response, and add the age-adjusted analysis as another supplementary table to the manuscript.

**Comment by qtran1** [comment]
To clarify, I only did the analysis comparing the gene expression between Cushing's (n=2) and Control (n=6) for patients that are older than 40 but <=60. Having age as a covariate in the model will cause quasi complete separation problem. That means age can perfectly separate the Cushing's and Control.

The overlap of our gene list (Cushing's adjusted for BMI) and the age-affected gene list PMID: 23889843 also has 11 genes.

![venncushing_age](https://cloud.githubusercontent.com/assets/6097135/7120214/1a149246-e1d1-11e4-8c3f-455694603ed7.jpg)

**Comment by davebridges** [comment]
Ah i understand I think just providing the data table for the 40-60 year old sub-cohort should be sufficient.  Are those 11 genes which were different in that sub-cohort also significant in the previous analysis?

**Comment by qtran1** [comment]
Don't know, will have to check!

**Comment by qtran1** [comment]
In our cohort, Cushing's subjects age ranges from 26 to 43 years old while age of control subjects ranges from 48 to 76. As a result, we divided subjects into 3 different age groups (0, 40], (40, 60], and (60, 100]. Although, we don't have any control patients that were younger than 40 years old nor any Cushing's patients that were older than 60, we have 6 control and 2 Cushing's subjects that had the age greater than 40 but <=60. We compared the gene expression between Cushing’s and controls in this age group and found 7 significant genes after adjusting for multiple hypothesis testing. These genes are HLA-DPB1I, PLOD2, CDKN2B, LHFPL2, S100B, ANXA5, and HLA-C (Supplementary Table 4). Among these 7 genes, PLOD2, CDKN2B and HLA-C were also significantly changed in the BMI-adjusted model.

Our current sample size does not allow us to add age as an extra covariate in our BMI-adjusted model. However, to demonstrate that significantly detected genes in our cohort were indeed affected by the Cushing’s disease and not confounded by age, we compared our gene list that was adjusted for BMI to a list of 185 genes that are affected by age in subcutaneous adipose tissues obtained from 856 female twins in the age range of 39-85 years (mean age 59.3 years) (PMID: 23889843). The overlap of our gene list and the age-affected gene list (p adjusted < 0.01 for both analyses) contains only 11 genes (i.e. ACACA, ACSS2, CLDN5, CLEC10A, ELOVL6, GCHFR, GPC6, HTATSF1, OLFM2, PNPLA3, and RET).

**Comment by davebridges** [comment]
I think we have to say something in the results, they ask us to address it in the methods or results section directly in their comment.  Even if we just say that due to small sample size we did not adjust for age in our analysis.

**Comment by davebridges** [comment]
Addressed in commit 1a5f2d2, Quynh can you proofread what i wrote and accept or change it before i send it to the rest of the coauthors

**Comment by qtran1** [comment]
I made some changes and pushed it back to github. It's good that we incorporated everything that were done to address this issue.
